# -*- coding: utf-8 -*-
"""DS SYPractical No.1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Cgd5PyU7-sEGDgF2mXSX-U_QxeGqv6Cs

#Practical No.1 
##Aim : Write a program to swap rows and columns of a given array in reverse order using NumPy.
"""

#import library
import numpy as np

#declare variable  
nums = np.array([['c1', 'c2', 'c3', 'c4'],
               [0, 1, 3, 4],
               [90, 91, 93, 94],
               [5, 0, 3, 2]])
print("Original array:")
print(nums)

num1=nums
num2=nums
print("\\n Swap rows of the said array in reverse order")
swap_row=nums[::-1,::]
print(swap_row)

"""# slicing from index start to index stop-1
arr[start:stop]

# slicing from index start to the end
arr[start:]

# slicing from the beginning to index stop - 1
arr[:stop]

# slicing from the index start to index stop, by skipping step
arr[start:stop:step]

# slicing from 1st to last in steps of 1 in reverse order
arr[::-1]
"""

print("\\n Swap columns of the said array in reverse order")
swap_col=num1[::,::-1]
print(swap_col)

# perfrom reverse operation on rows and
print("\nSwap rows and columns of the said array in reverse order:")
new_nums = num1[::-1, ::-1]
print(new_nums)

#
import numpy as np
my_array = np.arange(12).reshape(3, 4)
print("Original array:")
print(my_array)
my_array[:,[0, 1]] = my_array[:,[1, 0]]
print("\nAfter swapping columns:")
print(my_array)

"""Create a NumPy ndarray Object

---


NumPy is used to work with arrays. The array object in NumPy is called ndarray.

We can create a NumPy ndarray object by using the array() function.

"""

import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(arr)

print(type(arr))

"""type(): This built-in Python function tells us the type of the object passed to it. Like in above code it shows that arr is numpy.ndarray type."""

#To create an ndarray, we can pass a list, tuple or any array-like object into the array() method, and it will be converted into an ndarray:
#Use a tuple to create a NumPy array:

import numpy as np

arr = np.array((1, 2, 3, 4, 5))

print(arr)

"""#Dimensions in Arrays

---

#0-D Arrays
0-D arrays, or Scalars, are the elements in an array. Each value in an array is a 0-D array. 

A dimension in arrays is one level of array depth (nested arrays).

nested array: are arrays that have arrays as their elements.
"""

#Create a 0-D array with value 42

import numpy as np

arr = np.array(42)

print(arr)

"""#1-D Arrays
An array that has 0-D arrays as its elements is called uni-dimensional or 1-D array.

These are the most common and basic arrays.
"""

#Create a 1-D array containing the values 1,2,3,4,5:

import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(arr)

import numpy as np
a=np.array([[13,12],[1,5]])
b=np.array([[2,6],[3,4]])

#np.dot(a,b)
c=a-b
#print(c)
print('1st Array : ')
print(a)
print('2nd Array : ')
print(b)

#a.ndim